version: '3.8'

services:
  crawl4ai:
    build: .
    image: crawl4ai-app:latest
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=8000
    restart: unless-stopped
    volumes:
      - .:/app  # Mount entire project directory
      - /app/__pycache__  # Exclude Python cache
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    # Optional: resource limits
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G 